### ISSUE TITLE
Why options doesnt work in online?

### ISSUE THREAD

**Issue by St6niaa** [Rahaboss/RDRMenu2#5]

**Comment by Rahaboss** [comment]
I don't make this trainer for online. Still, I don't know why it doesn't work in online, there are no explicit blocks I have put in to stop that. The natives wouldn't need to be updated either. In fact differently from GTA 5 the native hashes don't change, so there is no crossmap needed.

**Comment by Rahaboss** [comment]
Also did you get it to work in offline mode? What is the console output for you in offline and online mode? Using Vulkan doesn't work either way, you need to use D3D12 in advanced graphics settings.

**Comment by St6niaa** [comment]
I maked this work in online! this is very simple man, but some buttons dont work, but I am still solving that, thanks for the source!

**Comment by St6niaa** [comment]
And one question, how I disable the context? The thing who shows OBJECT: PED: and etc

**Comment by Rahaboss** [comment]
That is under the rendering features. I was experimenting with it before, but have added toggles in new commits.
