### ISSUE TITLE
Crashing when Inject

### ISSUE THREAD

**Issue by St6niaa** [Rahaboss/RDRMenu2#7]
Hello! When I inject your source, my game crashes before creating the renderer, when starting renderer, crashes, you can help me? I tried solve but without result

**Comment by St6niaa** [comment]
My problem before this was the processor, AVX doesnt work with my processor, I changed to SSE2 and worked, but the menu is crashing

**Comment by Rahaboss** [comment]
What renderer are you using, DirectX12 or Vulkan? Some programs that render on the game like FPS counters might be causing some problems. Try to disable things like Rivatuner, Discord overlay, Steam overlay or whatever you have and maybe that will fix it.

**Comment by St6niaa** [comment]
I'm using DirectX12, the ImGui Vulkan is with problems on my ImGui lib, I used your base a time ago, but it's in version 1, and DirectX 12 without Vulkan worked normal, but ok, i'll test! Do you have discord? I want to show you what I make and etc

**Comment by Rahaboss** [comment]
Yes, you can add me on discord @radianccy
